# Generated by Django 2.2 on 2020-12-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote_author',
            field=models.CharField(max_length=30),
        ),
    ]
